baseURL = "https://gsken.vercel.app/"
languageCode = "id-ID"
title = "RGN Internet - Internet Super Cepat & Stabil"
disableKinds = ["taxonomy", "taxonomyTerm"]
theme = "rgn-theme"

[params]
  description = "Nikmati koneksi fiber optik tanpa batas dari RGN Internet, ideal untuk work from home, streaming, dan gaming."

[menu]
  [[menu.main]]
    name = "Beranda"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Layanan"
    url = "#layanan"
    weight = 2
  [[menu.main]]
    name = "Paket"
    url = "#paket"
    weight = 3
  [[menu.main]]
    name = "Testimoni"
    url = "#testimoni"
    weight = 4